[theme]
primaryColor = "#009E8E"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B1538"
font = "sans serif"
baseRadius = "large"
buttonRadius = "large"
showWidgetBorder = true
showSidebarBorder = true

[server]
headless = true

[browser]
gatherUsageStats = false